# Site settings
title: Centreville Code and Coffee
email: centrevillecodecoffee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Centreville Code and Coffee
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://centrevillecodecoffee.github.io" # the base hostname & protocol for your site
twitter_username: cvlcodecoffee
github_username:  centrevillecodecoffee

# Build settings
markdown: kramdown
